import type { FindingAnalysis, SustainabilityBug } from '@greenops/detect';

/**
 * A candidate fix for a sustainability bug, with everything needed to compare
 * options and simulate their effect before touching anything.
 */
export interface FixStrategy {
  id: string;
  title: string;
  /** What the fix does. */
  description: string;
  /** Fraction of the bug's waste this fix is expected to remove (0..1). */
  expectedReductionFactor: number;
  /** How risky/invasive the change is. */
  effort: 'trivial' | 'small' | 'moderate';
  /** Whether the change is easily reversible (guardrail preference). */
  reversible: boolean;
}

/** Root-cause + option analysis produced by the Investigate/Compare stages. */
export interface Investigation {
  rootCause: string;
  strategies: FixStrategy[];
  recommendedStrategyId: string;
  reasoning: string;
  /** Reported tokens, null if usage is unknown (0 for explicitly offline work). */
  tokensUsed: number | null;
  /** Per-finding provenance, including tokens consumed by rejected model output. */
  analysis?: FindingAnalysis;
  /** Optional concrete code suggestion or fix snippet generated by LLM. */
  suggestedCode?: string;
}

/**
 * The Reasoner performs Investigate + Compare. It is pluggable so the PoC runs
 * fully offline with a deterministic rule-based reasoner (zero tokens, zero keys —
 * a judge can run it with no setup), and a real LLM reasoner can be dropped in
 * for a richer demo. Both satisfy the same contract.
 */
export interface Reasoner {
  readonly name: string;
  /** Used to classify failed attempts; unclassified failures are conservatively unknown LLM usage. */
  readonly usesModel?: boolean;
  investigate(bug: SustainabilityBug, codeSnippet?: string): Promise<Investigation>;
}

/** Outcome of the human-in-the-loop approval gate. */
export interface ApprovalDecision {
  approved: boolean;
  approver: string;
  reason?: string;
}

/**
 * The Approver is the human oversight guardrail. In the PoC CLI it prompts the
 * operator; in autopilot/CI it can auto-approve only trivial+reversible fixes and
 * escalate everything else — the policy is explicit and logged.
 */
export interface Approver {
  readonly name: string;
  decide(bug: SustainabilityBug, investigation: Investigation): Promise<ApprovalDecision>;
}
